### ISSUE TITLE
Incompatable with Custom user models with migrations in Django 1.8

### ISSUE THREAD

**Issue by JesseCrocker** [pinax/pinax-notifications#45] opened 2015-04-06 18:46 UTC
After upgrading to Django 1.8 I am not able to initialize a new database with syncdb/migrate .

The problem is with unmigrated models that depend on migrated models, in this case pinax.notifications. NoticeSetting and a custom user model that is migrated.

According to a ticket in the Django bug tracker this is not due to a bug in django, but due to a bug that was fixed, where previously constraints on non-existant tables where silently ingored, they now cause an error.

Django bug https://code.djangoproject.com/ticket/24311
Test case https://github.com/JesseCrocker/testcase-django-1.8-customuser-migration-order

**Comment by grapemix** [comment] 2015-06-09 23:14
+1

Same situation here.

My temp solution is run 
1) django-admin.py makemigrations APP_NAME
2) django-admin.py migrate APP_NAME            <--- And it will fail, but you need to run it
3) django-admin.py migrate

For testcase, I am stuck too.

**Comment by JesseCrocker** [comment] 2015-06-10 13:52
@grapemix If you need a solution that doesn't generate errors, fork this repo, makemigrations for pinax-notifications, use the fork

**Comment by grapemix** [comment] 2015-06-13 21:44
thx, @JesseCrocker. I don't use pinax-notifications. I was googling the migration problem and try to support the django and python community. It turned out one of my app is using south migration format and led to the problem. After I convert the migration file format, everything including testcase is fine. Anyway, thx.

**Comment by qasimalbaqali** [comment] 2015-06-17 23:16
+1, any idea if this is on their radar of stuff to be fixed?

**Comment by paltman** [comment] 2015-06-19 03:52
Should be fixed in #48

**Closed by paltman** 2015-06-19 03:52 UTC

**Comment by grapemix** [comment] 2015-06-19 05:25
@qasimalbaqali, in my case, the problem is caused by one of my app is dependent on my custom user model and the app's migration file is the old south migration. In that case, that app is regarded as unmigrated app and being migrated at the beginning. But the custom user model migration is in the migrated which AFTER the unmigrated app. As you can see, the problematic app is migrated without custom user migration and hence caused the problem. Check all your apps which used custom user model and dig into Django's code if you still have problem. 

Happy hacking.
